#!/bin/sh

STAGING_DIR="${HOME}/mediatek/OpenWrt-SDK-ramips-mt7688_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir"
export STAGING_DIR
BINDIR=${STAGING_DIR}/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/bin
INCDIR=${STAGING_DIR}/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include
LIBDIR=${STAGING_DIR}/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib
CROSS_PREFIX=mipsel-openwrt-linux-
PATH=${PATH}:${BINDIR}
export PATH
${CROSS_PREFIX}gcc -I$INCDIR -L$LIBDIR -Wall program.c gpio_interface.c -o program || exit
scp ./program root@mylinkit.local:program
