#!/bin/sh

export CC_TOOLS=/home/training/mediatek/OpenWrt-Toolchain-ramips-mt7688_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2
$CC_TOOLS/bin/mipsel-openwrt-linux-g++ program.c -o program
scp ./program root@mylinkit.local:program
